logging.file: pilincs-logs.txt
spring:
# because of data safety it is recommended to overwrite this property at application startup from command line, not here
  jpa.hibernate.ddl-auto: none
#  jpa.hibernate.ddl-auto: create-drop
  jackson.serialization.INDENT_OUTPUT: true
server:
  contextPath: /pilincs
panorama:
  connectionUrl: https://panoramaweb.org/labkey
  folders: LINCS/P100,LINCS/GCP
  runIdUrl: https://panoramaweb.org/labkey/targetedms/LINCS/%s/showPrecursorList.view?id=%d
  gctDownloadUrl: https://panoramaweb.org/labkey/targetedms/LINCS/%s/RunGCTReport.view?runId=%d&reportName=GCT%%20File%%20%s&processed=%s
  gctDownloadUrl2: https://panoramaweb.org/labkey/lincs/LINCS/%s/RunGCTReport.view?runId=%d&reportName=GCT%%20File%%20%s&GCT_input_peptidearearatio.RunId~eq=%d&processed=%s
  peptideInternalIdUrl: https://panoramaweb.org/labkey/query/LINCS/%s/selectRows.view?schemaName=targetedms&query.queryName=PeptideAnnotation&query.Name~eq=pr_id&query.Value~in=%s&query.PeptideId/PeptideGroupId/RunId/Id~eq=%d
  chromatogramUrl: https://panoramaweb.org/labkey/targetedms/LINCS/%s/showPeptide.view?id=%d&annotationsFilter=id%%20%%3A%%20%s
  peptideAnnotationsUrl: https://panoramaweb.org/labkey/query/LINCS/%s/selectRows.api?schemaName=targetedms&query.queryName=peptideannotation
  replicateAnnotationsUrl: https://panoramaweb.org/labkey/query/LINCS/%s/selectRows.api?schemaName=targetedms&query.queryName=replicateannotation

---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: mysql
  datasource:
    #url: jdbc:mysql://localhost/pilincs
    #url: jdbc:mysql://10.165.4.32:3306/pilincs_20160205
    url: jdbc:mysql://10.165.104.119:3306/pilincs
    driverClassName: com.mysql.jdbc.Driver
    username: pilincs
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect